# Generated by Django 2.2.10 on 2021-12-04 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('0', 'Текст'), ('1', 'Единичный'), ('2', 'Множественный')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer', to='surveys.Surveys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
